name: Bug Report
description: File a bug report
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of kaboom are you running?
      options:
        - v2000.1
        - v2000.0
        - v0.x
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: live-demo
    attributes:
      label: Live demo
      description: If there's a live demo of the bug
      placeholder: https://yourdomain.tld/game
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happend that should not happen.
      placeholder: I see horror beyond imagination...
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What's the expected behavior?
      description: What is the expected behavior
      placeholder: It should do ...
    validations:
      required: true
